services:
  php:
    container_name: php
    build:
      context: ./php
      args:
        - PUID=${PUID}
        - PGID=${PGID}
    image: mcrm-php-fpm:1.0.0
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    working_dir: /var/www/html
    tty: true
    environment:
      TZ: Asia/Tashkent
    volumes:
      - ./../project/:/var/www/html:rw
    depends_on:
      - db

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    image: mcrm-nginx:1.0.0
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    tty: true
    environment:
      TZ: Asia/Tashkent
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
    volumes:
      - ./../project/:/var/www/html:rw
    depends_on:
      - php

  db:
    container_name: pgsql
    image: "postgres:16.3-alpine3.20"
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD:-secret}"
      POSTGRES_USER: "${DB_USER:-postgres}"
      POSTGRES_DB: "${DB_NAME:-postgres}"
      TZ: Asia/Tashkent
      PGTZ: Asia/Tashkent
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/postgresql.conf:/etc/postgresql.conf:ro
    ports:
      - "127.0.0.1:${DB_PORT:-5432}:5432"
    command:
      - "postgres"
      - "-c"
      - "config_file=/etc/postgresql.conf"

  adminer:
    container_name: adminer
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080

volumes:
  db_data:

  # redis:
  #     container_name: redis
  #     image: "redis:alpine"
  #     restart: unless-stopped
  #     environment:
  #         TZ: Asia/Tashkent
  #     volumes:
  #         - "./docker/data/redis:/data"
  #     ports:
  #         - "127.0.0.1:${REDIS_PORT:-6379}:6379"
  # db:
  #   container_name: mysql
  #   image: "mariadb:10.5.2"
  #   restart: unless-stopped
  #   environment:
  #     MYSQL_ROOT_PASSWORD: "${DB_PASSWORD:-example}"
  #     MYSQL_ROOT_HOST: "%"
  #     MYSQL_DATABASE: "${DB_NAME:-example}"
  #     MYSQL_USER: "${DB_USER:-example}"
  #     MYSQL_PASSWORD: "${DB_PASSWORD:-example}"
  #     TZ: Asia/Tashkent
  #   volumes:
  #     - "db_data:/var/lib/mysql"
  #   ports:
  #     - "127.0.0.1:${DB_PORT:-3306}:3306"
  #   command:
  #     [
  #         'mysqld',
  #         '--character-set-server=utf8mb4',
  #         '--collation-server=utf8mb4_general_ci'
  #     ]